version: "3.1"

services:
  test:
    build: .    
    container_name: test
    restart: always
    command: tail -f /dev/null
    environment:
      api_key: "3TyIPv1vdVZxQixfBYrQT6yYwY5RQElB"
    ports:
      - 8001:8001
    volumes:
      - .:/test_task
